import { createContext, useContext, useEffect, useState, ReactNode } from "react";

// Supported languages: English, Arabic + 22 scheduled languages of India
export type Lang =
  | "en" | "ar"
  | "hi" | "ta" | "te" | "kn" | "ml" | "bn" | "mr" | "gu" | "pa"
  | "or" | "as" | "ur" | "sa" | "ne" | "ks" | "sd" | "kok" | "mni"
  | "doi" | "brx" | "sat" | "mai";

export const LANG_META: { code: Lang; label: string; short: string; rtl?: boolean }[] = [
  { code: "en", label: "English", short: "EN" },
  { code: "ar", label: "العربية", short: "AR", rtl: true },
  { code: "hi", label: "हिन्दी", short: "HI" },
  { code: "ta", label: "தமிழ்", short: "TA" },
  { code: "te", label: "తెలుగు", short: "TE" },
  { code: "kn", label: "ಕನ್ನಡ", short: "KN" },
  { code: "ml", label: "മലയാളം", short: "ML" },
  { code: "bn", label: "বাংলা", short: "BN" },
  { code: "mr", label: "मराठी", short: "MR" },
  { code: "gu", label: "ગુજરાતી", short: "GU" },
  { code: "pa", label: "ਪੰਜਾਬੀ", short: "PA" },
  { code: "or", label: "ଓଡ଼ିଆ", short: "OR" },
  { code: "as", label: "অসমীয়া", short: "AS" },
  { code: "ur", label: "اردو", short: "UR", rtl: true },
  { code: "sa", label: "संस्कृतम्", short: "SA" },
  { code: "ne", label: "नेपाली", short: "NE" },
  { code: "ks", label: "كٲشُر", short: "KS", rtl: true },
  { code: "sd", label: "سنڌي", short: "SD", rtl: true },
  { code: "kok", label: "कोंकणी", short: "KOK" },
  { code: "mni", label: "মৈতৈলোন্", short: "MNI" },
  { code: "doi", label: "डोगरी", short: "DOI" },
  { code: "brx", label: "बड़ो", short: "BRX" },
  { code: "sat", label: "ᱥᱟᱱᱛᱟᱲᱤ", short: "SAT" },
  { code: "mai", label: "मैथिली", short: "MAI" },
];

type Dict = Record<string, string>;

// Helper: keys used everywhere
const KEYS = [
  "nav.home","nav.about","nav.skills","nav.services","nav.portfolio","nav.contact","nav.hireMe",
  "hero.greeting","hero.role","hero.roleSuffix","hero.intro","hero.viewPortfolio","hero.contactMe",
  "about.title1","about.title2","about.p1","about.p2","about.education","about.eduLine1","about.eduLine2",
  "about.experience","about.expLine1","about.expLine2","about.languages","about.langLine1","about.langLine2",
  "skills.title1","skills.title2","skills.cat.core","skills.cat.ecom","skills.cat.tools",
  "services.title1","services.title2",
  "svc.uiux.title","svc.uiux.desc","svc.web.title","svc.web.desc","svc.ecom.title","svc.ecom.desc",
  "svc.dm.title","svc.dm.desc","svc.sm.title","svc.sm.desc","svc.photo.title","svc.photo.desc",
  "svc.video.title","svc.video.desc","svc.email.title","svc.email.desc",
  "portfolio.title1","portfolio.title2","portfolio.subtitle",
  "proj.vr.title","proj.vr.desc","proj.vr.cta",
  "proj.builder.title","proj.builder.desc","proj.builder.cta",
  "proj.scale.title","proj.scale.desc","proj.scale.cta",
  "proj.jobx.title","proj.jobx.desc","proj.jobx.cta",
  "proj.iilf.title","proj.iilf.desc","proj.iilf.cta",
  "proj.news.title","proj.news.desc","proj.news.cta",
  "contact.title1","contact.title2","contact.subtitle","contact.name","contact.email","contact.message",
  "contact.send","contact.location","contact.toastTitle","contact.toastDesc",
  "footer.rights","lang.label",
] as const;

const en: Dict = {
  "nav.home": "Home", "nav.about": "About", "nav.skills": "Skills", "nav.services": "Services",
  "nav.portfolio": "Portfolio", "nav.contact": "Contact", "nav.hireMe": "Hire Me",
  "hero.greeting": "Hey, I am",
  "hero.role": "Flutter Developer",
  "hero.roleSuffix": "· UI/UX Designer · E-commerce Specialist",
  "hero.intro": "I am a UI/UX designer and e-commerce specialist from Chennai with experience in WordPress, digital marketing, product management, and multimedia design.",
  "hero.viewPortfolio": "View Portfolio", "hero.contactMe": "Contact Me",
  "about.title1": "About", "about.title2": "Me",
  "about.p1": "A passionate UI/UX designer and e-commerce executive with extensive experience in digital operations, WordPress development, product management, and multimedia design. I bring creative vision and strategic thinking to every project, helping brands build strong digital identities.",
  "about.p2": "Based in Chennai, I specialize in crafting user-centric digital experiences that drive engagement and conversions. My multidisciplinary background allows me to bridge the gap between design, technology, and business strategy.",
  "about.education": "Education",
  "about.eduLine1": "Diploma in Automobile Engineering",
  "about.eduLine2": "Aalim Muhammed Salegh Polytechnic College · 2012–2015",
  "about.experience": "Experience",
  "about.expLine1": "Assistant Manager – IT at Leather Sector Skill Council",
  "about.expLine2": "6.5+ years in IT, UI/UX, e-commerce operations & digital marketing",
  "about.languages": "Languages",
  "about.langLine1": "English – Read, Write, Speak",
  "about.langLine2": "Tamil – Read, Write, Speak · Hindi – Speak",
  "skills.title1": "My", "skills.title2": "Skills",
  "skills.cat.core": "Core Skills", "skills.cat.ecom": "E-commerce Skills", "skills.cat.tools": "Software & Tools",
  "services.title1": "My", "services.title2": "Services",
  "svc.uiux.title": "UI/UX Design", "svc.uiux.desc": "User-centered interfaces with intuitive interactions and clean aesthetics.",
  "svc.web.title": "Website Design", "svc.web.desc": "Responsive WordPress websites built for performance and conversion.",
  "svc.ecom.title": "E-commerce Support", "svc.ecom.desc": "End-to-end e-commerce setup, product listing, and catalog management.",
  "svc.dm.title": "Digital Marketing", "svc.dm.desc": "Creative campaigns and SEO strategies to grow your online presence.",
  "svc.sm.title": "Social Media Design", "svc.sm.desc": "Eye-catching social media creatives that boost engagement.",
  "svc.photo.title": "Product Photography", "svc.photo.desc": "Professional product shoots optimized for web and social media.",
  "svc.video.title": "Videography", "svc.video.desc": "Video production and editing for brands and digital platforms.",
  "svc.email.title": "Email Campaigns", "svc.email.desc": "Newsletter design and email campaign creation with Mailchimp.",
  "portfolio.title1": "Featured", "portfolio.title2": "Projects",
  "portfolio.subtitle": "A selection of my work across multimedia design, branding, and interactive experiences.",
  "proj.vr.title": "VR Immersive Learning Content",
  "proj.vr.desc": "Interactive VR educational experience designed for immersive learning environments.",
  "proj.vr.cta": "Watch Demo",
  "proj.builder.title": "Sri Gowralaya Builders",
  "proj.builder.desc": "WordPress real estate website with property listings, search, and CMS integration.",
  "proj.builder.cta": "Visit Website",
  "proj.scale.title": "Scale Ind 4.0 – IoT Dashboard",
  "proj.scale.desc": "UI/UX prototype for an industrial IoT monitoring dashboard with real-time analytics.",
  "proj.scale.cta": "View Prototype",
  "proj.jobx.title": "JobX – NSDC Hackathon",
  "proj.jobx.desc": "24-hour design sprint creating a job portal concept for web and mobile platforms.",
  "proj.jobx.cta": "View Project",
  "proj.iilf.title": "IILF 39th India International Leather Fair",
  "proj.iilf.desc": "Complete branding and print design for India's premier leather industry exhibition.",
  "proj.iilf.cta": "View Designs",
  "proj.news.title": "LSSC Newsletter",
  "proj.news.desc": "Digital publication design with modern editorial layouts and visual storytelling.",
  "proj.news.cta": "Preview Newsletter",
  "contact.title1": "Get in", "contact.title2": "Touch",
  "contact.subtitle": "Have a project in mind? Let's talk.",
  "contact.name": "Your Name", "contact.email": "Your Email", "contact.message": "Your Message",
  "contact.send": "Send Message", "contact.location": "Chennai, India",
  "contact.toastTitle": "Opening email client!",
  "contact.toastDesc": "Your default email app will open with the message pre-filled.",
  "footer.rights": "All rights reserved.", "lang.label": "Language",
};

const ta: Dict = {
  "nav.home": "முகப்பு", "nav.about": "என்னைப் பற்றி", "nav.skills": "திறன்கள்", "nav.services": "சேவைகள்",
  "nav.portfolio": "போர்ட்ஃபோலியோ", "nav.contact": "தொடர்பு", "nav.hireMe": "என்னை பணியமர்த்துங்கள்",
  "hero.greeting": "வணக்கம், நான்", "hero.role": "Flutter டெவலப்பர்",
  "hero.roleSuffix": "· UI/UX வடிவமைப்பாளர் · இ-காமர்ஸ் நிபுணர்",
  "hero.intro": "நான் சென்னையைச் சேர்ந்த UI/UX வடிவமைப்பாளர் மற்றும் இ-காமர்ஸ் நிபுணர். WordPress, டிஜிட்டல் மார்க்கெட்டிங், தயாரிப்பு மேலாண்மை மற்றும் மல்டிமீடியா வடிவமைப்பில் அனுபவம் உண்டு.",
  "hero.viewPortfolio": "போர்ட்ஃபோலியோ பார்க்க", "hero.contactMe": "என்னை தொடர்பு கொள்ளவும்",
  "about.title1": "என்னைப்", "about.title2": "பற்றி",
  "about.p1": "டிஜிட்டல் செயல்பாடுகள், WordPress மேம்பாடு, தயாரிப்பு மேலாண்மை மற்றும் மல்டிமீடியா வடிவமைப்பில் விரிவான அனுபவம் கொண்ட ஆர்வமுள்ள UI/UX வடிவமைப்பாளர் மற்றும் இ-காமர்ஸ் நிர்வாகி.",
  "about.p2": "சென்னையை தளமாகக் கொண்டு, ஈடுபாட்டையும் மாற்றங்களையும் தூண்டும் பயனர்-மைய டிஜிட்டல் அனுபவங்களை உருவாக்குவதில் நிபுணத்துவம் பெற்றுள்ளேன்.",
  "about.education": "கல்வி", "about.eduLine1": "டிப்ளமோ - ஆட்டோமொபைல் இன்ஜினியரிங்",
  "about.eduLine2": "ஆலிம் முகமது சாலே பாலிடெக்னிக் கல்லூரி · 2012–2015",
  "about.experience": "அனுபவம்", "about.expLine1": "உதவி மேலாளர் – IT, லெதர் செக்டார் ஸ்கில் கவுன்சில்",
  "about.expLine2": "IT, UI/UX, இ-காமர்ஸ் மற்றும் டிஜிட்டல் மார்க்கெட்டிங்கில் 6.5+ ஆண்டுகள்",
  "about.languages": "மொழிகள்", "about.langLine1": "ஆங்கிலம் – படிக்க, எழுத, பேச",
  "about.langLine2": "தமிழ் – படிக்க, எழுத, பேச · இந்தி – பேச",
  "skills.title1": "எனது", "skills.title2": "திறன்கள்",
  "skills.cat.core": "முக்கிய திறன்கள்", "skills.cat.ecom": "இ-காமர்ஸ் திறன்கள்", "skills.cat.tools": "மென்பொருள் & கருவிகள்",
  "services.title1": "எனது", "services.title2": "சேவைகள்",
  "svc.uiux.title": "UI/UX வடிவமைப்பு", "svc.uiux.desc": "உள்ளுணர்வு தொடர்புகள் மற்றும் தூய்மையான வடிவமைப்புடன் பயனர் மைய இடைமுகங்கள்.",
  "svc.web.title": "வலைத்தள வடிவமைப்பு", "svc.web.desc": "செயல்திறன் மற்றும் மாற்றத்திற்காக கட்டமைக்கப்பட்ட பதிலளிக்கக்கூடிய WordPress தளங்கள்.",
  "svc.ecom.title": "இ-காமர்ஸ் ஆதரவு", "svc.ecom.desc": "முழுமையான இ-காமர்ஸ் அமைப்பு, தயாரிப்பு பட்டியல் மற்றும் பட்டியல் மேலாண்மை.",
  "svc.dm.title": "டிஜிட்டல் மார்க்கெட்டிங்", "svc.dm.desc": "உங்கள் ஆன்லைன் இருப்பை வளர்க்க படைப்பு பிரச்சாரங்கள் மற்றும் SEO உத்திகள்.",
  "svc.sm.title": "சமூக ஊடக வடிவமைப்பு", "svc.sm.desc": "ஈடுபாட்டை அதிகரிக்கும் கவர்ச்சிகரமான சமூக ஊடக படைப்புகள்.",
  "svc.photo.title": "தயாரிப்பு புகைப்படம்", "svc.photo.desc": "வலை மற்றும் சமூக ஊடகங்களுக்காக தொழில்முறை தயாரிப்பு புகைப்படங்கள்.",
  "svc.video.title": "வீடியோ தயாரிப்பு", "svc.video.desc": "பிராண்டுகள் மற்றும் டிஜிட்டல் தளங்களுக்கான வீடியோ தயாரிப்பு மற்றும் எடிட்டிங்.",
  "svc.email.title": "மின்னஞ்சல் பிரச்சாரங்கள்", "svc.email.desc": "Mailchimp மூலம் செய்திமடல் வடிவமைப்பு மற்றும் மின்னஞ்சல் பிரச்சாரம்.",
  "portfolio.title1": "சிறப்பு", "portfolio.title2": "திட்டங்கள்",
  "portfolio.subtitle": "மல்டிமீடியா வடிவமைப்பு, பிராண்டிங் மற்றும் ஊடாடும் அனுபவங்களில் எனது பணியின் தேர்வு.",
  "proj.vr.title": "VR ஆழ்ந்த கற்றல் உள்ளடக்கம்",
  "proj.vr.desc": "ஆழ்ந்த கற்றல் சூழல்களுக்காக வடிவமைக்கப்பட்ட ஊடாடும் VR கல்வி அனுபவம்.",
  "proj.vr.cta": "டெமோ பார்க்க",
  "proj.builder.title": "ஸ்ரீ கௌரளய பில்டர்ஸ்",
  "proj.builder.desc": "சொத்து பட்டியல், தேடல் மற்றும் CMS ஒருங்கிணைப்புடன் கூடிய WordPress ரியல் எஸ்டேட் தளம்.",
  "proj.builder.cta": "தளத்தை பார்வையிட",
  "proj.scale.title": "Scale Ind 4.0 – IoT டாஷ்போர்டு",
  "proj.scale.desc": "நிகழ்நேர பகுப்பாய்வுகளுடன் தொழில்துறை IoT கண்காணிப்பு டாஷ்போர்டிற்கான UI/UX முன்மாதிரி.",
  "proj.scale.cta": "முன்மாதிரியை பார்க்க",
  "proj.jobx.title": "JobX – NSDC ஹேக்கத்தான்",
  "proj.jobx.desc": "வலை மற்றும் மொபைல் தளங்களுக்கான வேலை போர்ட்டல் கருத்தை உருவாக்கிய 24-மணிநேர வடிவமைப்பு ஸ்பிரிண்ட்.",
  "proj.jobx.cta": "திட்டத்தை பார்க்க",
  "proj.iilf.title": "IILF 39வது இந்தியா சர்வதேச தோல் கண்காட்சி",
  "proj.iilf.desc": "இந்தியாவின் முதன்மை தோல் தொழில் கண்காட்சிக்கான முழுமையான பிராண்டிங் மற்றும் அச்சு வடிவமைப்பு.",
  "proj.iilf.cta": "வடிவமைப்புகளை பார்க்க",
  "proj.news.title": "LSSC செய்திமடல்",
  "proj.news.desc": "நவீன ஆசிரியர் தளவமைப்புகள் மற்றும் காட்சி கதைசொல்லலுடன் டிஜிட்டல் வெளியீடு வடிவமைப்பு.",
  "proj.news.cta": "செய்திமடலை முன்னோட்டம்",
  "contact.title1": "தொடர்பில்", "contact.title2": "இருங்கள்",
  "contact.subtitle": "ஒரு திட்டம் மனதில் உள்ளதா? பேசுவோம்.",
  "contact.name": "உங்கள் பெயர்", "contact.email": "உங்கள் மின்னஞ்சல்", "contact.message": "உங்கள் செய்தி",
  "contact.send": "செய்தி அனுப்பு", "contact.location": "சென்னை, இந்தியா",
  "contact.toastTitle": "மின்னஞ்சல் கிளையன்ட் திறக்கப்படுகிறது!",
  "contact.toastDesc": "உங்கள் இயல்புநிலை மின்னஞ்சல் ஆப்ஸ் முன்-நிரப்பப்பட்ட செய்தியுடன் திறக்கும்.",
  "footer.rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.", "lang.label": "மொழி",
};

const hi: Dict = {
  "nav.home": "होम", "nav.about": "मेरे बारे में", "nav.skills": "कौशल", "nav.services": "सेवाएं",
  "nav.portfolio": "पोर्टफोलियो", "nav.contact": "संपर्क", "nav.hireMe": "मुझे हायर करें",
  "hero.greeting": "नमस्ते, मैं हूँ", "hero.role": "Flutter डेवलपर",
  "hero.roleSuffix": "· UI/UX डिज़ाइनर · ई-कॉमर्स विशेषज्ञ",
  "hero.intro": "मैं चेन्नई से एक UI/UX डिज़ाइनर और ई-कॉमर्स विशेषज्ञ हूँ, जिसके पास WordPress, डिजिटल मार्केटिंग, प्रोडक्ट मैनेजमेंट और मल्टीमीडिया डिज़ाइन का अनुभव है।",
  "hero.viewPortfolio": "पोर्टफोलियो देखें", "hero.contactMe": "मुझसे संपर्क करें",
  "about.title1": "मेरे", "about.title2": "बारे में",
  "about.p1": "एक भावुक UI/UX डिज़ाइनर और ई-कॉमर्स कार्यकारी जिसके पास डिजिटल ऑपरेशंस, WordPress विकास, प्रोडक्ट मैनेजमेंट और मल्टीमीडिया डिज़ाइन का व्यापक अनुभव है।",
  "about.p2": "चेन्नई में स्थित, मैं उपयोगकर्ता-केंद्रित डिजिटल अनुभवों को तैयार करने में विशेषज्ञता रखता हूँ जो जुड़ाव और रूपांतरण को बढ़ाते हैं।",
  "about.education": "शिक्षा", "about.eduLine1": "ऑटोमोबाइल इंजीनियरिंग में डिप्लोमा",
  "about.eduLine2": "आलिम मुहम्मद सालेग पॉलिटेक्निक कॉलेज · 2012–2015",
  "about.experience": "अनुभव", "about.expLine1": "सहायक प्रबंधक – IT, लेदर सेक्टर स्किल काउंसिल",
  "about.expLine2": "IT, UI/UX, ई-कॉमर्स और डिजिटल मार्केटिंग में 6.5+ वर्ष",
  "about.languages": "भाषाएँ", "about.langLine1": "अंग्रेजी – पढ़ें, लिखें, बोलें",
  "about.langLine2": "तमिल – पढ़ें, लिखें, बोलें · हिंदी – बोलें",
  "skills.title1": "मेरे", "skills.title2": "कौशल",
  "skills.cat.core": "मुख्य कौशल", "skills.cat.ecom": "ई-कॉमर्स कौशल", "skills.cat.tools": "सॉफ़्टवेयर और टूल्स",
  "services.title1": "मेरी", "services.title2": "सेवाएं",
  "svc.uiux.title": "UI/UX डिज़ाइन", "svc.uiux.desc": "सहज इंटरैक्शन और साफ़ सौंदर्य के साथ उपयोगकर्ता-केंद्रित इंटरफेस।",
  "svc.web.title": "वेबसाइट डिज़ाइन", "svc.web.desc": "प्रदर्शन और रूपांतरण के लिए बनाई गई रिस्पॉन्सिव WordPress वेबसाइटें।",
  "svc.ecom.title": "ई-कॉमर्स सहायता", "svc.ecom.desc": "एंड-टू-एंड ई-कॉमर्स सेटअप, उत्पाद सूची और कैटलॉग प्रबंधन।",
  "svc.dm.title": "डिजिटल मार्केटिंग", "svc.dm.desc": "आपकी ऑनलाइन उपस्थिति बढ़ाने के लिए रचनात्मक अभियान और SEO रणनीतियाँ।",
  "svc.sm.title": "सोशल मीडिया डिज़ाइन", "svc.sm.desc": "आकर्षक सोशल मीडिया क्रिएटिव जो जुड़ाव बढ़ाते हैं।",
  "svc.photo.title": "उत्पाद फोटोग्राफी", "svc.photo.desc": "वेब और सोशल मीडिया के लिए अनुकूलित पेशेवर उत्पाद शूट।",
  "svc.video.title": "वीडियोग्राफी", "svc.video.desc": "ब्रांडों और डिजिटल प्लेटफॉर्म के लिए वीडियो उत्पादन और संपादन।",
  "svc.email.title": "ईमेल अभियान", "svc.email.desc": "Mailchimp के साथ न्यूज़लेटर डिज़ाइन और ईमेल अभियान निर्माण।",
  "portfolio.title1": "विशेष", "portfolio.title2": "प्रोजेक्ट्स",
  "portfolio.subtitle": "मल्टीमीडिया डिज़ाइन, ब्रांडिंग और इंटरैक्टिव अनुभवों में मेरे काम का चयन।",
  "proj.vr.title": "VR इमर्सिव लर्निंग कंटेंट",
  "proj.vr.desc": "इमर्सिव लर्निंग वातावरण के लिए डिज़ाइन किया गया इंटरैक्टिव VR शैक्षिक अनुभव।",
  "proj.vr.cta": "डेमो देखें",
  "proj.builder.title": "श्री गौरालय बिल्डर्स",
  "proj.builder.desc": "प्रॉपर्टी लिस्टिंग, सर्च और CMS एकीकरण के साथ WordPress रियल एस्टेट वेबसाइट।",
  "proj.builder.cta": "वेबसाइट देखें",
  "proj.scale.title": "Scale Ind 4.0 – IoT डैशबोर्ड",
  "proj.scale.desc": "रीयल-टाइम एनालिटिक्स के साथ औद्योगिक IoT मॉनिटरिंग डैशबोर्ड के लिए UI/UX प्रोटोटाइप।",
  "proj.scale.cta": "प्रोटोटाइप देखें",
  "proj.jobx.title": "JobX – NSDC हैकाथॉन",
  "proj.jobx.desc": "वेब और मोबाइल प्लेटफॉर्म के लिए जॉब पोर्टल कॉन्सेप्ट बनाने वाला 24 घंटे का डिज़ाइन स्प्रिंट।",
  "proj.jobx.cta": "प्रोजेक्ट देखें",
  "proj.iilf.title": "IILF 39वां इंडिया इंटरनेशनल लेदर फेयर",
  "proj.iilf.desc": "भारत की प्रमुख चमड़ा उद्योग प्रदर्शनी के लिए संपूर्ण ब्रांडिंग और प्रिंट डिज़ाइन।",
  "proj.iilf.cta": "डिज़ाइन देखें",
  "proj.news.title": "LSSC न्यूज़लेटर",
  "proj.news.desc": "आधुनिक संपादकीय लेआउट और दृश्य कहानी कहने के साथ डिजिटल प्रकाशन डिज़ाइन।",
  "proj.news.cta": "न्यूज़लेटर पूर्वावलोकन",
  "contact.title1": "संपर्क", "contact.title2": "में रहें",
  "contact.subtitle": "क्या आपके मन में कोई प्रोजेक्ट है? बात करते हैं।",
  "contact.name": "आपका नाम", "contact.email": "आपका ईमेल", "contact.message": "आपका संदेश",
  "contact.send": "संदेश भेजें", "contact.location": "चेन्नई, भारत",
  "contact.toastTitle": "ईमेल क्लाइंट खुल रहा है!",
  "contact.toastDesc": "आपका डिफ़ॉल्ट ईमेल ऐप पहले से भरे संदेश के साथ खुलेगा।",
  "footer.rights": "सर्वाधिकार सुरक्षित।", "lang.label": "भाषा",
};

const ar: Dict = {
  "nav.home": "الرئيسية", "nav.about": "نبذة عني", "nav.skills": "المهارات", "nav.services": "الخدمات",
  "nav.portfolio": "الأعمال", "nav.contact": "اتصل بي", "nav.hireMe": "وظفني",
  "hero.greeting": "مرحباً، أنا", "hero.role": "مطوّر Flutter",
  "hero.roleSuffix": "· مصمم UI/UX · أخصائي تجارة إلكترونية",
  "hero.intro": "أنا مصمم UI/UX وأخصائي تجارة إلكترونية من تشيناي، لدي خبرة في WordPress والتسويق الرقمي وإدارة المنتجات وتصميم الوسائط المتعددة.",
  "hero.viewPortfolio": "عرض الأعمال", "hero.contactMe": "تواصل معي",
  "about.title1": "نبذة", "about.title2": "عني",
  "about.p1": "مصمم UI/UX شغوف وتنفيذي تجارة إلكترونية يتمتع بخبرة واسعة في العمليات الرقمية وتطوير WordPress وإدارة المنتجات وتصميم الوسائط المتعددة.",
  "about.p2": "مقيم في تشيناي، متخصص في تصميم تجارب رقمية تركز على المستخدم لزيادة التفاعل والتحويلات.",
  "about.education": "التعليم", "about.eduLine1": "دبلوم في هندسة السيارات",
  "about.eduLine2": "كلية عاليم محمد صالح بوليتكنك · 2012–2015",
  "about.experience": "الخبرة", "about.expLine1": "مساعد مدير – تكنولوجيا المعلومات في مجلس مهارات قطاع الجلود",
  "about.expLine2": "أكثر من 6.5 سنوات في IT و UI/UX والتجارة الإلكترونية والتسويق الرقمي",
  "about.languages": "اللغات", "about.langLine1": "الإنجليزية – قراءة، كتابة، تحدث",
  "about.langLine2": "التاميلية – قراءة، كتابة، تحدث · الهندية – تحدث",
  "skills.title1": "مهاراتي", "skills.title2": "",
  "skills.cat.core": "المهارات الأساسية", "skills.cat.ecom": "مهارات التجارة الإلكترونية", "skills.cat.tools": "البرامج والأدوات",
  "services.title1": "خدماتي", "services.title2": "",
  "svc.uiux.title": "تصميم UI/UX", "svc.uiux.desc": "واجهات تركز على المستخدم بتفاعلات بديهية وجماليات نظيفة.",
  "svc.web.title": "تصميم المواقع", "svc.web.desc": "مواقع WordPress متجاوبة مصممة للأداء والتحويل.",
  "svc.ecom.title": "دعم التجارة الإلكترونية", "svc.ecom.desc": "إعداد كامل للتجارة الإلكترونية وإدراج المنتجات وإدارة الكتالوج.",
  "svc.dm.title": "التسويق الرقمي", "svc.dm.desc": "حملات إبداعية واستراتيجيات SEO لتنمية حضورك على الإنترنت.",
  "svc.sm.title": "تصميم وسائل التواصل", "svc.sm.desc": "إبداعات ملفتة لوسائل التواصل الاجتماعي تعزز التفاعل.",
  "svc.photo.title": "تصوير المنتجات", "svc.photo.desc": "تصوير احترافي للمنتجات محسّن للويب ووسائل التواصل.",
  "svc.video.title": "إنتاج الفيديو", "svc.video.desc": "إنتاج وتحرير الفيديو للعلامات التجارية والمنصات الرقمية.",
  "svc.email.title": "حملات البريد الإلكتروني", "svc.email.desc": "تصميم النشرات وإنشاء حملات البريد الإلكتروني عبر Mailchimp.",
  "portfolio.title1": "مشاريع", "portfolio.title2": "مميزة",
  "portfolio.subtitle": "مجموعة مختارة من أعمالي في تصميم الوسائط المتعددة والعلامات التجارية والتجارب التفاعلية.",
  "proj.vr.title": "محتوى تعليمي غامر بالواقع الافتراضي",
  "proj.vr.desc": "تجربة تعليمية تفاعلية بالواقع الافتراضي مصممة لبيئات التعلم الغامرة.",
  "proj.vr.cta": "شاهد العرض",
  "proj.builder.title": "Sri Gowralaya Builders",
  "proj.builder.desc": "موقع عقاري WordPress مع قوائم العقارات والبحث وتكامل CMS.",
  "proj.builder.cta": "زيارة الموقع",
  "proj.scale.title": "Scale Ind 4.0 – لوحة تحكم IoT",
  "proj.scale.desc": "نموذج UI/UX للوحة مراقبة IoT صناعية مع تحليلات في الوقت الفعلي.",
  "proj.scale.cta": "عرض النموذج",
  "proj.jobx.title": "JobX – هاكاثون NSDC",
  "proj.jobx.desc": "سباق تصميم 24 ساعة لإنشاء مفهوم بوابة وظائف للويب والجوال.",
  "proj.jobx.cta": "عرض المشروع",
  "proj.iilf.title": "IILF معرض الجلود الدولي 39 بالهند",
  "proj.iilf.desc": "علامة تجارية كاملة وتصميم مطبوع لأهم معرض لصناعة الجلود في الهند.",
  "proj.iilf.cta": "عرض التصاميم",
  "proj.news.title": "نشرة LSSC",
  "proj.news.desc": "تصميم منشور رقمي بتخطيطات تحريرية حديثة وسرد بصري.",
  "proj.news.cta": "معاينة النشرة",
  "contact.title1": "تواصل", "contact.title2": "معي",
  "contact.subtitle": "هل لديك مشروع في ذهنك؟ لنتحدث.",
  "contact.name": "اسمك", "contact.email": "بريدك الإلكتروني", "contact.message": "رسالتك",
  "contact.send": "إرسال الرسالة", "contact.location": "تشيناي، الهند",
  "contact.toastTitle": "جاري فتح تطبيق البريد!",
  "contact.toastDesc": "سيفتح تطبيق البريد الافتراضي مع رسالة جاهزة.",
  "footer.rights": "جميع الحقوق محفوظة.", "lang.label": "اللغة",
};

// Compact translations for additional Indian scheduled languages.
// Keys not present here fall back to English automatically.
const partials: Record<string, Partial<Dict>> = {
  te: { // Telugu
    "nav.home": "హోమ్", "nav.about": "నా గురించి", "nav.skills": "నైపుణ్యాలు", "nav.services": "సేవలు",
    "nav.portfolio": "పోర్ట్‌ఫోలియో", "nav.contact": "సంప్రదించండి", "nav.hireMe": "నన్ను నియమించండి",
    "hero.greeting": "హలో, నేను", "hero.viewPortfolio": "పోర్ట్‌ఫోలియో చూడండి", "hero.contactMe": "నన్ను సంప్రదించండి",
    "about.title1": "నా", "about.title2": "గురించి",
    "skills.title1": "నా", "skills.title2": "నైపుణ్యాలు",
    "services.title1": "నా", "services.title2": "సేవలు",
    "portfolio.title1": "ప్రముఖ", "portfolio.title2": "ప్రాజెక్టులు",
    "contact.title1": "సంప్రదించండి", "contact.title2": "",
    "contact.send": "సందేశం పంపండి",
    "footer.rights": "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.", "lang.label": "భాష",
  },
  kn: { // Kannada
    "nav.home": "ಮುಖಪುಟ", "nav.about": "ನನ್ನ ಬಗ್ಗೆ", "nav.skills": "ಕೌಶಲ್ಯಗಳು", "nav.services": "ಸೇವೆಗಳು",
    "nav.portfolio": "ಪೋರ್ಟ್‌ಫೋಲಿಯೋ", "nav.contact": "ಸಂಪರ್ಕ", "nav.hireMe": "ನನ್ನನ್ನು ನೇಮಿಸಿ",
    "hero.greeting": "ನಮಸ್ಕಾರ, ನಾನು", "hero.viewPortfolio": "ಪೋರ್ಟ್‌ಫೋಲಿಯೋ ನೋಡಿ", "hero.contactMe": "ನನ್ನನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "about.title1": "ನನ್ನ", "about.title2": "ಬಗ್ಗೆ",
    "skills.title1": "ನನ್ನ", "skills.title2": "ಕೌಶಲ್ಯಗಳು",
    "services.title1": "ನನ್ನ", "services.title2": "ಸೇವೆಗಳು",
    "portfolio.title1": "ವೈಶಿಷ್ಟ್ಯ", "portfolio.title2": "ಯೋಜನೆಗಳು",
    "contact.title1": "ಸಂಪರ್ಕದಲ್ಲಿ", "contact.title2": "ಇರಿ",
    "contact.send": "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "footer.rights": "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.", "lang.label": "ಭಾಷೆ",
  },
  ml: { // Malayalam
    "nav.home": "ഹോം", "nav.about": "എന്നെക്കുറിച്ച്", "nav.skills": "കഴിവുകൾ", "nav.services": "സേവനങ്ങൾ",
    "nav.portfolio": "പോർട്ട്‌ഫോളിയോ", "nav.contact": "ബന്ധപ്പെടുക", "nav.hireMe": "എന്നെ നിയമിക്കൂ",
    "hero.greeting": "ഹായ്, ഞാൻ", "hero.viewPortfolio": "പോർട്ട്‌ഫോളിയോ കാണുക", "hero.contactMe": "എന്നെ ബന്ധപ്പെടുക",
    "about.title1": "എന്നെ", "about.title2": "ക്കുറിച്ച്",
    "skills.title1": "എന്റെ", "skills.title2": "കഴിവുകൾ",
    "services.title1": "എന്റെ", "services.title2": "സേവനങ്ങൾ",
    "portfolio.title1": "പ്രത്യേക", "portfolio.title2": "പ്രോജക്ടുകൾ",
    "contact.title1": "ബന്ധപ്പെടുക", "contact.title2": "",
    "contact.send": "സന്ദേശം അയയ്ക്കുക",
    "footer.rights": "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.", "lang.label": "ഭാഷ",
  },
  bn: { // Bengali
    "nav.home": "হোম", "nav.about": "আমার সম্পর্কে", "nav.skills": "দক্ষতা", "nav.services": "পরিষেবা",
    "nav.portfolio": "পোর্টফোলিও", "nav.contact": "যোগাযোগ", "nav.hireMe": "আমাকে নিয়োগ দিন",
    "hero.greeting": "হ্যালো, আমি", "hero.viewPortfolio": "পোর্টফোলিও দেখুন", "hero.contactMe": "যোগাযোগ করুন",
    "about.title1": "আমার", "about.title2": "সম্পর্কে",
    "skills.title1": "আমার", "skills.title2": "দক্ষতা",
    "services.title1": "আমার", "services.title2": "পরিষেবা",
    "portfolio.title1": "বিশেষ", "portfolio.title2": "প্রকল্প",
    "contact.title1": "যোগাযোগে", "contact.title2": "থাকুন",
    "contact.send": "বার্তা পাঠান",
    "footer.rights": "সর্বস্বত্ব সংরক্ষিত।", "lang.label": "ভাষা",
  },
  mr: { // Marathi
    "nav.home": "मुख्यपृष्ठ", "nav.about": "माझ्याबद्दल", "nav.skills": "कौशल्ये", "nav.services": "सेवा",
    "nav.portfolio": "पोर्टफोलिओ", "nav.contact": "संपर्क", "nav.hireMe": "मला नियुक्त करा",
    "hero.greeting": "नमस्कार, मी", "hero.viewPortfolio": "पोर्टफोलिओ पहा", "hero.contactMe": "संपर्क करा",
    "about.title1": "माझ्या", "about.title2": "बद्दल",
    "skills.title1": "माझी", "skills.title2": "कौशल्ये",
    "services.title1": "माझ्या", "services.title2": "सेवा",
    "portfolio.title1": "विशेष", "portfolio.title2": "प्रकल्प",
    "contact.title1": "संपर्कात", "contact.title2": "रहा",
    "contact.send": "संदेश पाठवा",
    "footer.rights": "सर्व हक्क राखीव.", "lang.label": "भाषा",
  },
  gu: { // Gujarati
    "nav.home": "હોમ", "nav.about": "મારા વિશે", "nav.skills": "કુશળતા", "nav.services": "સેવાઓ",
    "nav.portfolio": "પોર્ટફોલિયો", "nav.contact": "સંપર્ક", "nav.hireMe": "મને હાયર કરો",
    "hero.greeting": "નમસ્તે, હું છું", "hero.viewPortfolio": "પોર્ટફોલિયો જુઓ", "hero.contactMe": "સંપર્ક કરો",
    "about.title1": "મારા", "about.title2": "વિશે",
    "skills.title1": "મારી", "skills.title2": "કુશળતા",
    "services.title1": "મારી", "services.title2": "સેવાઓ",
    "portfolio.title1": "વિશેષ", "portfolio.title2": "પ્રોજેક્ટ્સ",
    "contact.title1": "સંપર્કમાં", "contact.title2": "રહો",
    "contact.send": "સંદેશ મોકલો",
    "footer.rights": "બધા હકો અનામત.", "lang.label": "ભાષા",
  },
  pa: { // Punjabi
    "nav.home": "ਹੋਮ", "nav.about": "ਮੇਰੇ ਬਾਰੇ", "nav.skills": "ਹੁਨਰ", "nav.services": "ਸੇਵਾਵਾਂ",
    "nav.portfolio": "ਪੋਰਟਫੋਲੀਓ", "nav.contact": "ਸੰਪਰਕ", "nav.hireMe": "ਮੈਨੂੰ ਹਾਇਰ ਕਰੋ",
    "hero.greeting": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਮੈਂ ਹਾਂ", "hero.viewPortfolio": "ਪੋਰਟਫੋਲੀਓ ਵੇਖੋ", "hero.contactMe": "ਸੰਪਰਕ ਕਰੋ",
    "about.title1": "ਮੇਰੇ", "about.title2": "ਬਾਰੇ",
    "skills.title1": "ਮੇਰੇ", "skills.title2": "ਹੁਨਰ",
    "services.title1": "ਮੇਰੀਆਂ", "services.title2": "ਸੇਵਾਵਾਂ",
    "portfolio.title1": "ਖਾਸ", "portfolio.title2": "ਪ੍ਰੋਜੈਕਟ",
    "contact.title1": "ਸੰਪਰਕ", "contact.title2": "ਕਰੋ",
    "contact.send": "ਸੁਨੇਹਾ ਭੇਜੋ",
    "footer.rights": "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ.", "lang.label": "ਭਾਸ਼ਾ",
  },
  or: { // Odia
    "nav.home": "ହୋମ୍", "nav.about": "ମୋ ବିଷୟରେ", "nav.skills": "ଦକ୍ଷତା", "nav.services": "ସେବା",
    "nav.portfolio": "ପୋର୍ଟଫୋଲିଓ", "nav.contact": "ଯୋଗାଯୋଗ", "nav.hireMe": "ମୋତେ ନିଯୁକ୍ତ କରନ୍ତୁ",
    "hero.greeting": "ନମସ୍କାର, ମୁଁ", "hero.viewPortfolio": "ପୋର୍ଟଫୋଲିଓ ଦେଖନ୍ତୁ", "hero.contactMe": "ଯୋଗାଯୋଗ କରନ୍ତୁ",
    "about.title1": "ମୋ", "about.title2": "ବିଷୟରେ",
    "skills.title1": "ମୋର", "skills.title2": "ଦକ୍ଷତା",
    "services.title1": "ମୋର", "services.title2": "ସେବା",
    "portfolio.title1": "ବିଶେଷ", "portfolio.title2": "ପ୍ରକଳ୍ପ",
    "contact.title1": "ଯୋଗାଯୋଗ", "contact.title2": "କରନ୍ତୁ",
    "contact.send": "ସନ୍ଦେଶ ପଠାନ୍ତୁ",
    "footer.rights": "ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ.", "lang.label": "ଭାଷା",
  },
  as: { // Assamese
    "nav.home": "হোম", "nav.about": "মোৰ বিষয়ে", "nav.skills": "দক্ষতা", "nav.services": "সেৱা",
    "nav.portfolio": "পৰ্টফলিঅ’", "nav.contact": "যোগাযোগ", "nav.hireMe": "মোক নিযুক্তি দিয়ক",
    "hero.greeting": "নমস্কাৰ, মই", "hero.viewPortfolio": "পৰ্টফলিঅ’ চাওক", "hero.contactMe": "যোগাযোগ কৰক",
    "about.title1": "মোৰ", "about.title2": "বিষয়ে",
    "skills.title1": "মোৰ", "skills.title2": "দক্ষতা",
    "services.title1": "মোৰ", "services.title2": "সেৱা",
    "portfolio.title1": "বিশেষ", "portfolio.title2": "প্ৰকল্প",
    "contact.title1": "যোগাযোগ", "contact.title2": "কৰক",
    "contact.send": "বাৰ্তা পঠাওক",
    "footer.rights": "সকলো অধিকাৰ সংৰক্ষিত.", "lang.label": "ভাষা",
  },
  ur: { // Urdu (RTL)
    "nav.home": "ہوم", "nav.about": "میرے بارے میں", "nav.skills": "مہارتیں", "nav.services": "خدمات",
    "nav.portfolio": "پورٹ فولیو", "nav.contact": "رابطہ", "nav.hireMe": "مجھے ہائر کریں",
    "hero.greeting": "ہیلو، میں ہوں", "hero.viewPortfolio": "پورٹ فولیو دیکھیں", "hero.contactMe": "رابطہ کریں",
    "about.title1": "میرے", "about.title2": "بارے میں",
    "skills.title1": "میری", "skills.title2": "مہارتیں",
    "services.title1": "میری", "services.title2": "خدمات",
    "portfolio.title1": "نمایاں", "portfolio.title2": "منصوبے",
    "contact.title1": "رابطے", "contact.title2": "میں رہیں",
    "contact.send": "پیغام بھیجیں",
    "footer.rights": "جملہ حقوق محفوظ ہیں.", "lang.label": "زبان",
  },
  sa: { // Sanskrit
    "nav.home": "गृहम्", "nav.about": "मम विषये", "nav.skills": "कौशलानि", "nav.services": "सेवाः",
    "nav.portfolio": "कार्यसङ्ग्रहः", "nav.contact": "सम्पर्कः", "nav.hireMe": "मां नियोजयतु",
    "hero.greeting": "नमस्ते, अहम्", "hero.viewPortfolio": "कार्यसङ्ग्रहं पश्यतु", "hero.contactMe": "सम्पर्कं करोतु",
    "about.title1": "मम", "about.title2": "विषये",
    "skills.title1": "मम", "skills.title2": "कौशलानि",
    "services.title1": "मम", "services.title2": "सेवाः",
    "portfolio.title1": "विशेषाः", "portfolio.title2": "कार्याणि",
    "contact.title1": "सम्पर्कं", "contact.title2": "करोतु",
    "contact.send": "सन्देशं प्रेषयतु",
    "footer.rights": "सर्वे अधिकाराः सुरक्षिताः.", "lang.label": "भाषा",
  },
  ne: { // Nepali
    "nav.home": "गृहपृष्ठ", "nav.about": "मेरो बारेमा", "nav.skills": "सीपहरू", "nav.services": "सेवाहरू",
    "nav.portfolio": "पोर्टफोलियो", "nav.contact": "सम्पर्क", "nav.hireMe": "मलाई हायर गर्नुहोस्",
    "hero.greeting": "नमस्ते, म हुँ", "hero.viewPortfolio": "पोर्टफोलियो हेर्नुहोस्", "hero.contactMe": "सम्पर्क गर्नुहोस्",
    "about.title1": "मेरो", "about.title2": "बारेमा",
    "skills.title1": "मेरा", "skills.title2": "सीपहरू",
    "services.title1": "मेरा", "services.title2": "सेवाहरू",
    "portfolio.title1": "विशेष", "portfolio.title2": "परियोजनाहरू",
    "contact.title1": "सम्पर्कमा", "contact.title2": "रहनुहोस्",
    "contact.send": "सन्देश पठाउनुहोस्",
    "footer.rights": "सर्वाधिकार सुरक्षित.", "lang.label": "भाषा",
  },
  ks: { // Kashmiri (RTL)
    "nav.home": "گٔر", "nav.about": "میٚہ مُتلِق", "nav.skills": "ہنر", "nav.services": "خدمات",
    "nav.portfolio": "پورٹ فولیو", "nav.contact": "رٲبطہٕ", "nav.hireMe": "میٚہ ہائر کٔرِو",
    "hero.greeting": "آداب، بہٕ چھس", "hero.viewPortfolio": "پورٹ فولیو وُچھِو", "hero.contactMe": "رٲبطہٕ کٔرِو",
    "about.title1": "میٚہ", "about.title2": "مُتلِق",
    "skills.title1": "میٚنۍ", "skills.title2": "ہنر",
    "services.title1": "میٚنۍ", "services.title2": "خدمات",
    "portfolio.title1": "خاص", "portfolio.title2": "پروجیکٹ",
    "contact.title1": "رٲبطہٕ", "contact.title2": "کٔرِو",
    "contact.send": "پیغام رٔوانہٕ کٔرِو",
    "footer.rights": "تمام حُقوق محفوظ.", "lang.label": "زبان",
  },
  sd: { // Sindhi (RTL)
    "nav.home": "گهر", "nav.about": "منهنجي باري ۾", "nav.skills": "صلاحيتون", "nav.services": "خدمتون",
    "nav.portfolio": "پورٽ فوليو", "nav.contact": "رابطو", "nav.hireMe": "مون کي ڀرتي ڪريو",
    "hero.greeting": "سلام، آءٌ آهيان", "hero.viewPortfolio": "پورٽ فوليو ڏسو", "hero.contactMe": "رابطو ڪريو",
    "about.title1": "منهنجي", "about.title2": "باري ۾",
    "skills.title1": "منهنجون", "skills.title2": "صلاحيتون",
    "services.title1": "منهنجون", "services.title2": "خدمتون",
    "portfolio.title1": "خاص", "portfolio.title2": "منصوبا",
    "contact.title1": "رابطي", "contact.title2": "۾ رهو",
    "contact.send": "پيغام موڪليو",
    "footer.rights": "سڀ حق محفوظ آهن.", "lang.label": "ٻولي",
  },
  kok: { // Konkani
    "nav.home": "मुखेल पान", "nav.about": "म्हजे विशीं", "nav.skills": "कुशळटायो", "nav.services": "सेवा",
    "nav.portfolio": "पोर्टफोलियो", "nav.contact": "संपर्क", "nav.hireMe": "म्हाका भरती करात",
    "hero.greeting": "नमस्कार, हांव", "hero.viewPortfolio": "पोर्टफोलियो पळयात", "hero.contactMe": "संपर्क करात",
    "about.title1": "म्हजे", "about.title2": "विशीं",
    "skills.title1": "म्हज्यो", "skills.title2": "कुशळटायो",
    "services.title1": "म्हज्यो", "services.title2": "सेवा",
    "portfolio.title1": "विशेश", "portfolio.title2": "प्रकल्प",
    "contact.title1": "संपर्क", "contact.title2": "करात",
    "contact.send": "संदेश धाडात",
    "footer.rights": "सगळे हक्क राखून दवरल्यात.", "lang.label": "भास",
  },
  mni: { // Manipuri (Meitei)
    "nav.home": "হোম", "nav.about": "ঐগী মরমদা", "nav.skills": "স্কিল", "nav.services": "সর্ভিস",
    "nav.portfolio": "পোর্টফোলিও", "nav.contact": "কন্টেক্ট", "nav.hireMe": "ঐবু হায়র তৌবিয়ু",
    "hero.greeting": "খুরুমজরী, ঐ", "hero.viewPortfolio": "পোর্টফোলিও য়েংবিয়ু", "hero.contactMe": "কন্টেক্ট তৌবিয়ু",
    "about.title1": "ঐগী", "about.title2": "মরমদা",
    "skills.title1": "ঐগী", "skills.title2": "স্কিল",
    "services.title1": "ঐগী", "services.title2": "সর্ভিস",
    "portfolio.title1": "অখন্নবা", "portfolio.title2": "প্রজেক্ট",
    "contact.title1": "কন্টেক্ট", "contact.title2": "তৌবিয়ু",
    "contact.send": "মেসেজ থাবিয়ু",
    "footer.rights": "অপুনবা হক্ক ঙাকপীয়ু.", "lang.label": "লোন",
  },
  doi: { // Dogri
    "nav.home": "घर", "nav.about": "मेरे बारे", "nav.skills": "हुनर", "nav.services": "सेवां",
    "nav.portfolio": "पोर्टफोलियो", "nav.contact": "संपर्क", "nav.hireMe": "मिगी हायर करो",
    "hero.greeting": "नमस्कार, मैं", "hero.viewPortfolio": "पोर्टफोलियो दिक्खो", "hero.contactMe": "संपर्क करो",
    "about.title1": "मेरे", "about.title2": "बारे",
    "skills.title1": "मेरे", "skills.title2": "हुनर",
    "services.title1": "मेरियां", "services.title2": "सेवां",
    "portfolio.title1": "खास", "portfolio.title2": "प्रोजेक्ट",
    "contact.title1": "संपर्क", "contact.title2": "करो",
    "contact.send": "संदेश भेजो",
    "footer.rights": "सब्भै हक्क सुरक्षित.", "lang.label": "भाशा",
  },
  brx: { // Bodo
    "nav.home": "नो", "nav.about": "आंनि सोमोन्दै", "nav.skills": "गुण", "nav.services": "सिबिथाय",
    "nav.portfolio": "पोर्टफोलियो", "nav.contact": "जगाजग", "nav.hireMe": "आंखौ हायर खालाम",
    "hero.greeting": "खुलुमबाय, आं", "hero.viewPortfolio": "पोर्टफोलियो नाय", "hero.contactMe": "जगाजग खालाम",
    "about.title1": "आंनि", "about.title2": "सोमोन्दै",
    "skills.title1": "आंनि", "skills.title2": "गुण",
    "services.title1": "आंनि", "services.title2": "सिबिथाय",
    "portfolio.title1": "गाहाय", "portfolio.title2": "प्रजेक्ट",
    "contact.title1": "जगाजग", "contact.title2": "खालाम",
    "contact.send": "खौरां दैथाय",
    "footer.rights": "गासै अधिकार रैखाथि जादों.", "lang.label": "रावथि",
  },
  sat: { // Santali (Ol Chiki)
    "nav.home": "ᱚᱲᱟᱜ", "nav.about": "ᱤᱧᱟᱜ ᱵᱟᱵᱚᱛ", "nav.skills": "ᱦᱩᱱᱟᱨ", "nav.services": "ᱥᱮᱵᱟ",
    "nav.portfolio": "ᱯᱳᱨᱴᱯᱷᱳᱞᱤᱭᱳ", "nav.contact": "ᱡᱚᱱᱚᱲᱟᱣ", "nav.hireMe": "ᱤᱧ ᱦᱟᱭᱨ ᱢᱮ",
    "hero.greeting": "ᱡᱚᱦᱟᱨ, ᱤᱧ ᱠᱟᱱᱟᱸ", "hero.viewPortfolio": "ᱯᱳᱨᱴᱯᱷᱳᱞᱤᱭᱳ ᱧᱮᱞ ᱢᱮ", "hero.contactMe": "ᱡᱚᱱᱚᱲᱟᱣ ᱢᱮ",
    "about.title1": "ᱤᱧᱟᱜ", "about.title2": "ᱵᱟᱵᱚᱛ",
    "skills.title1": "ᱤᱧᱟᱜ", "skills.title2": "ᱦᱩᱱᱟᱨ",
    "services.title1": "ᱤᱧᱟᱜ", "services.title2": "ᱥᱮᱵᱟ",
    "portfolio.title1": "ᱵᱟᱪᱷᱟᱣᱟᱱ", "portfolio.title2": "ᱯᱨᱳᱡᱮᱠᱴ",
    "contact.title1": "ᱡᱚᱱᱚᱲᱟᱣ", "contact.title2": "ᱢᱮ",
    "contact.send": "ᱠᱷᱚᱵᱚᱨ ᱠᱩᱞ ᱢᱮ",
    "footer.rights": "ᱡᱚᱛᱚ ᱦᱚᱠ ᱨᱟᱠᱷᱟ ᱟᱠᱟᱱᱟ.", "lang.label": "ᱯᱟᱹᱨᱥᱤ",
  },
  mai: { // Maithili
    "nav.home": "घर", "nav.about": "हमरा बारे में", "nav.skills": "कौशल", "nav.services": "सेवा",
    "nav.portfolio": "पोर्टफोलियो", "nav.contact": "संपर्क", "nav.hireMe": "हमरा हायर करू",
    "hero.greeting": "प्रणाम, हम छी", "hero.viewPortfolio": "पोर्टफोलियो देखू", "hero.contactMe": "संपर्क करू",
    "about.title1": "हमरा", "about.title2": "बारे में",
    "skills.title1": "हमर", "skills.title2": "कौशल",
    "services.title1": "हमर", "services.title2": "सेवा",
    "portfolio.title1": "विशेष", "portfolio.title2": "प्रोजेक्ट",
    "contact.title1": "संपर्क", "contact.title2": "करू",
    "contact.send": "संदेश पठाऊ",
    "footer.rights": "सर्वाधिकार सुरक्षित.", "lang.label": "भाषा",
  },
};

// Build full dictionary by merging partials with English fallback
const buildDict = (partial: Partial<Dict>): Dict => ({ ...en, ...partial });

const translations: Record<Lang, Dict> = {
  en, ar, hi, ta,
  te: buildDict(partials.te),
  kn: buildDict(partials.kn),
  ml: buildDict(partials.ml),
  bn: buildDict(partials.bn),
  mr: buildDict(partials.mr),
  gu: buildDict(partials.gu),
  pa: buildDict(partials.pa),
  or: buildDict(partials.or),
  as: buildDict(partials.as),
  ur: buildDict(partials.ur),
  sa: buildDict(partials.sa),
  ne: buildDict(partials.ne),
  ks: buildDict(partials.ks),
  sd: buildDict(partials.sd),
  kok: buildDict(partials.kok),
  mni: buildDict(partials.mni),
  doi: buildDict(partials.doi),
  brx: buildDict(partials.brx),
  sat: buildDict(partials.sat),
  mai: buildDict(partials.mai),
};

const SUPPORTED: Lang[] = LANG_META.map((l) => l.code);

const detectBrowserLang = (): Lang => {
  if (typeof navigator === "undefined") return "en";
  const candidates = [...(navigator.languages ?? []), navigator.language ?? ""];
  for (const raw of candidates) {
    if (!raw) continue;
    const lower = raw.toLowerCase();
    const base = lower.split("-")[0] as Lang;
    if (SUPPORTED.includes(base)) return base;
    // Special mappings
    if (lower.startsWith("ar")) return "ar";
    if (lower.startsWith("ne")) return "ne";
  }
  return "en";
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const stored = localStorage.getItem("lang") as Lang | null;
    if (stored && SUPPORTED.includes(stored)) return stored;
    return detectBrowserLang();
  });

  const isRTL = LANG_META.find((l) => l.code === lang)?.rtl ?? false;

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
  }, [lang, isRTL]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
